name: Docker image build

on: [push]

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v3
    - name: dokcer build image for csharp
      run : |
        docker build ./c# -t muzakkirsaifi/csharp:1.0
    # - name: docker image for the golang
    #   run: |
    #     docker build ./golang -t muzakkirsaifi/golang:1.0
    - name: docker image for the nodejs
      run: |
        docker build ./nodejs -t muzakkirsaifi/nodejs:1.0
    - name: docker image for the python
      run: |
        docker build ./python -t muzakkirsaifi/python:1.0


