name: Docker image build

on: 
  workflow_dispatch: 

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v3
    - name: docker login  
      env: 
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: dokcer build image for csharp
      run : |
        docker build ./c# -t muzakkirsaifi/csharp:1.0
    # - name: docker image for the golang
    #   run: |
    #     docker build ./golang -t muzakkirsaifi/golang:1.0
    - name: docker image for the nodejs
      run: |
        docker build ./nodejs -t muzakkirsaifi/nodejs:1.0
    - name: docker image for the python
      run: |
        docker build ./python -t muzakkirsaifi/python:1.0

    - name: Docekr push the image
      run : |
        docker push muzakkirsaifi/csharp:1.0
        docker push muzakkirsaifi/nodejs:1.0
        docker push muzakkirsaifi/python:1.0


